"""Drop templates_spec_params and spec_values tables

Revision ID: 5b5fc81420bb
Revises: a28d62139a07
Create Date: 2026-08-21 10:46:57.334578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b5fc81420bb'
down_revision: Union[str, Sequence[str], None] = 'a28d62139a07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nodes_protocoles_spec_params_values', if_exists=True)
    op.drop_table('template_spec_params', if_exists=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('template_spec_params',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('tmp_id', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tmp_id'], ['proto_templates.id'], name=op.f('template_spec_params_tmp_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('template_spec_params_pkey')),
    sa.UniqueConstraint('tmp_id', 'key', name=op.f('template_spec_params_tmp_id_key_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('nodes_protocoles_spec_params_values',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('spec_key_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('node_proto_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['node_proto_id'], ['nodes_protocols.id'], name=op.f('nodes_protocoles_spec_params_values_node_proto_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['spec_key_id'], ['template_spec_params.id'], name=op.f('nodes_protocoles_spec_params_values_spec_key_id_fkey'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('nodes_protocoles_spec_params_values_pkey')),
    sa.UniqueConstraint('spec_key_id', 'node_proto_id', name=op.f('nodes_protocoles_spec_params_valu_spec_key_id_node_proto_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    if_not_exists=True,
    )
    # ### end Alembic commands ###
