"""drop protocols proto_commands. add fk np.tmp_id

Revision ID: 8c7b68981995
Revises: 90869d01d30c
Create Date: 2026-09-21 09:26:05.710987

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy import text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c7b68981995'
down_revision: Union[str, Sequence[str], None] = '90869d01d30c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    op.drop_constraint(op.f('nodes_proto_id_fkey'), 'nodes_protocols', type_='foreignkey', if_exists=True)
    op.drop_column('nodes_protocols', 'proto_id', if_exists=True)

    # Проверяем, существует ли внешний ключ nodes_protocols_tmp_id_fkey
    fk_exists = conn.execute(
        text("""
        SELECT EXISTS (
            SELECT 1 FROM information_schema.table_constraints
            WHERE constraint_name = 'nodes_protocols_tmp_id_fkey'
            AND table_name = 'nodes_protocols'
            AND constraint_type = 'FOREIGN KEY'
        )
    """)
    ).scalar()

    if not fk_exists:
        op.create_foreign_key(
            'nodes_protocols_tmp_id_fkey', 'nodes_protocols', 'proto_templates', ['tmp_id'], ['id'], ondelete='RESTRICT'
        )
        print('Внешний ключ "np.tmp_id -> pt.id" создан')
    else:
        print('Внешний ключ "np.tmp_id -> pt.id" уже существует. Скип')

    op.drop_table('protocols_commands', if_exists=True)
    op.drop_table('protocols', if_exists=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()

    op.create_table(
        'protocols',
        sa.Column(
            'id',
            sa.SMALLINT(),
            sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=32767, cycle=False, cache=1),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            'name',
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=False,
            comment='Название протокола (xray, wireguard, openvpn и т.д.)',
        ),
        sa.Column(
            'created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True
        ),
        sa.Column('tmp_id', sa.SMALLINT(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ['tmp_id'], ['proto_templates.id'], name=op.f('protocols_proto_tmp_id_fkey'), ondelete='RESTRICT'
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('protocols_pkey')),
        sa.UniqueConstraint(
            'name', name=op.f('protocols_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False
        ),
        comment='Пул поддерживаемых VPN протоколов',
        if_not_exists=True,
    )

    op.create_table(
        'protocols_commands',
        sa.Column(
            'id',
            sa.BIGINT(),
            sa.Identity(
                always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1
            ),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column('proto_id', sa.SMALLINT(), autoincrement=False, nullable=False, comment='ID протокола'),
        sa.Column(
            'cmd_title',
            sa.VARCHAR(length=200),
            autoincrement=False,
            nullable=False,
            comment='Название команды (add_user, remove_user, restart и т.д.)',
        ),
        sa.Column(
            'command',
            sa.TEXT(),
            autoincrement=False,
            nullable=False,
            comment='Полная CLI команда для выполнения. Валидация не производится - ответственность администратора',
        ),
        sa.Column(
            'created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True
        ),
        sa.Column('admin_id', sa.BIGINT(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], name=op.f('protocols_commands_admin_id_fkey')),
        sa.ForeignKeyConstraint(
            ['proto_id'], ['protocols.id'], name=op.f('protocols_commands_proto_id_fkey'), ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('protocols_commands_pkey')),
        comment='CLI команды для управления протоколами',
        if_not_exists=True,
    )

    op.add_column(
        'nodes_protocols', sa.Column('proto_id', sa.SMALLINT(), autoincrement=False, nullable=True), if_not_exists=True
    )
    op.drop_constraint('nodes_protocols_tmp_id_fkey', 'nodes_protocols', type_='foreignkey', if_exists=True)

    # Проверяем, существует ли внешний ключ nodes_protocols_tmp_id_fkey
    fk_exists = conn.execute(
        text("""
        SELECT EXISTS (
            SELECT 1 FROM information_schema.table_constraints
            WHERE constraint_name = 'nodes_proto_id_fkey'
            AND table_name = 'nodes_protocols'
            AND constraint_type = 'FOREIGN KEY'
        )
    """)
    ).scalar()

    if not fk_exists:
        op.create_foreign_key(
            op.f('nodes_proto_id_fkey'), 'nodes_protocols', 'protocols', ['proto_id'], ['id'], ondelete='RESTRICT'
        )
        print('Внешний ключ "np.tmp_id -> pt.id" создан')
    else:
        print('Внешний ключ "np.tmp_id -> pt.id" уже существует. Скип')
    # ### end Alembic commands ###
