"""change vatchar size for proto_python_lib

Revision ID: 8dbdccfe2431
Revises: 5b5fc81420bb
Create Date: 2026-08-24 14:49:53.120747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision: str = '8dbdccfe2431'
down_revision: Union[str, Sequence[str], None] = '5b5fc81420bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.alter_column('proto_templates', 'proto_python_lib',
                    existing_type=sa.VARCHAR(length=32),
                    type_=sa.String(length=512),
                    existing_nullable=True)

    # Проверяем существование constraint
    conn = op.get_bind()
    inspector = inspect(conn)
    constraints = [c['name'] for c in inspector.get_unique_constraints('templates_users_extractors')]

    if 'templates_users_extractors_tmp_id_flatten_array_cursor_key' not in constraints:
        op.create_unique_constraint(
            'templates_users_extractors_tmp_id_flatten_array_cursor_key',
            'templates_users_extractors',
            ['tmp_id', 'flatten_array_cursor']
        )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('templates_users_extractors_tmp_id_flatten_array_cursor_key', 'templates_users_extractors', type_='unique')
    op.alter_column('proto_templates', 'proto_python_lib',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
    # ### end Alembic commands ###
