"""add json_column for core cmds

Revision ID: 90869d01d30c
Revises: 654f5bd3b65a
Create Date: 2026-09-21 09:01:16.017818

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision: str = '90869d01d30c'
down_revision: Union[str, Sequence[str], None] = '654f5bd3b65a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    EXPAND PHASE

    Protocols приговорена к сносу. nodes_protocols будет ссылаться на tmp_id
    Proto_commands - будет удалена. Для управления ядрами cli командами используем pt.cli_cmds
    """
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()

    "Nodes_Protocols"
    op.add_column(
        'nodes_protocols',
        sa.Column('service_name', sa.String(length=256), nullable=True),
        if_not_exists=True,
    )
    op.add_column('nodes_protocols', sa.Column('tmp_id', sa.Integer(), nullable=True), if_not_exists=True)

    # Проверяем, существует ли таблица protocols
    table_exists = conn.execute(
        text("""
        SELECT EXISTS (
            SELECT FROM information_schema.tables
            WHERE table_schema = 'public'
            AND table_name = 'protocols'
        )
    """)
    ).scalar()

    if table_exists:
        exists_vnodes = conn.execute(
            text('''
            UPDATE nodes_protocols SET tmp_id = inp.tmp_id FROM (
            SELECT np.id AS node_proto_id, p.tmp_id FROM nodes_protocols np
            JOIN protocols p ON p.id = np.proto_id
            ) AS inp
            WHERE inp.node_proto_id = nodes_protocols.id
            RETURNING id
        ''')
        ).fetchall()
        print(f'Мигрировано виртуальных нод ("proto_id -> tmp_id"): \033[34m{len(exists_vnodes)}\033[0m')
    else:
        print('Таблица protocols не существует. Миграция nodes_protocols пропущена')

    op.add_column(
        'proto_templates',
        sa.Column('cli_cmds', sa.JSON(), server_default=sa.text('\'{"commands": []}\'::json'), nullable=True),
        if_not_exists=True,
    )

    op.alter_column(
        'proto_templates',
        'id',
        existing_type=sa.SMALLINT(),
        type_=sa.Integer(),
        existing_nullable=False,
        existing_server_default=sa.Identity(
            always=True, start=1, increment=1, minvalue=1, maxvalue=32767, cycle=False, cache=1
        ),
    )
    op.drop_column('proto_templates', 'reload_core_command', if_exists=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'proto_templates',
        sa.Column('reload_core_command', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
        if_not_exists=True,
    )
    op.alter_column(
        'proto_templates',
        'id',
        existing_type=sa.Integer(),
        type_=sa.SMALLINT(),
        existing_nullable=False,
        existing_server_default=sa.Identity(
            always=True, start=1, increment=1, minvalue=1, maxvalue=32767, cycle=False, cache=1
        ),
    )
    op.drop_column('proto_templates', 'cli_cmds', if_exists=True)
    op.drop_column('nodes_protocols', 'tmp_id', if_exists=True)
    op.drop_column('nodes_protocols', 'service_name', if_exists=True)
    # ### end Alembic commands ###
