"""add constant_node_data_obj nodes_protocols

Revision ID: a28d62139a07
Revises: e3f4a8b9c1d2
Create Date: 2026-08-19 08:06:00.635753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a28d62139a07'
down_revision: Union[str, Sequence[str], None] = 'e3f4a8b9c1d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        '''
        ALTER TABLE nodes_protocols ADD COLUMN IF NOT EXISTS constant_node_data_obj jsonb DEFAULT '{}'::jsonb;
        '''
    )
    # op.add_column('nodes_protocols', sa.Column('constant_node_data_obj', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes_protocols', 'constant_node_data_obj')
    # ### end Alembic commands ###
