"""improvements template system

Revision ID: bfc8c7642691
Revises: 8dbdccfe2431
Create Date: 2026-08-31 11:58:41.782912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfc8c7642691'
down_revision: Union[str, Sequence[str], None] = '8dbdccfe2431'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes_protocols', sa.Column('reload_core_command', sa.String(length=256), nullable=True), if_not_exists=True)
    op.add_column('nodes_protocols', sa.Column('metrics_command', sa.String(length=256), nullable=True), if_not_exists=True)
    op.add_column('proto_templates', sa.Column('config2json_script', sa.Text(), nullable=True), if_not_exists=True)
    op.add_column('proto_templates', sa.Column('json2config_script', sa.Text(), nullable=True), if_not_exists=True)
    op.add_column('proto_templates', sa.Column('conf_converter_libs', sa.String(length=512), nullable=True), if_not_exists=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proto_templates', 'conf_converter_libs', if_exists=True)
    op.drop_column('proto_templates', 'json2config_script', if_exists=True)
    op.drop_column('proto_templates', 'config2json_script', if_exists=True)
    op.drop_column('nodes_protocols', 'metrics_command', if_exists=True)
    op.drop_column('nodes_protocols', 'reload_core_command', if_exists=True)
    # ### end Alembic commands ###
