"""initial_schema_empty_db

Revision ID: ceb3071c66c1
Revises: 
Create Date: 2026-08-04 12:21:56.669621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ceb3071c66c1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('passw', sa.String(length=97), nullable=False),
    sa.Column('login', sa.String(length=128), nullable=False),
    sa.Column('date_register', sa.Date(), server_default=sa.text('(now())::date'), nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('login', name='admins_login_key')
    )
    op.create_table('nodes',
    sa.Column('id', sa.SmallInteger(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=32767, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('api_port', sa.Integer(), nullable=False),
    sa.Column('private_ip', sa.String(length=45), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.Time(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('node_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id', name='nodes_pkey1'),
    sa.UniqueConstraint('ip', name='nodes_ip_key'),
    sa.UniqueConstraint('private_ip', name='nodes_private_ip_key')
    )
    op.create_table('online_statuses',
    sa.Column('id', sa.SmallInteger(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=32767, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', name='online_statuses_pkey')
    )
    op.create_table('pay_statuses',
    sa.Column('id', sa.SmallInteger(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=32767, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pay_statuses_pkey'),
    sa.UniqueConstraint('name', name='pay_statuses_name_key')
    )
    op.create_table('remote_execute_history',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('command', sa.String(length=1024), nullable=False),
    sa.Column('stdout', sa.Text(), nullable=True),
    sa.Column('stderr', sa.Text(), nullable=True),
    sa.Column('exit_code', sa.Integer(), server_default=sa.text('1'), nullable=True),
    sa.Column('exception_text', sa.Text(), nullable=True),
    sa.Column('node_proto_id', sa.Integer(), nullable=True),
    sa.Column('api_port', sa.Integer(), nullable=True),
    sa.Column('private_ip', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('status_code', sa.SmallInteger(), server_default=sa.text('100'), nullable=True),
    sa.Column('node_success', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name='remote_execute_history_pkey')
    )
    op.create_table('sub_nodes_operations',
    sa.Column('id', sa.SmallInteger(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=32767, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id', name='add_core_proto_statuses_pkey')
    )
    op.create_table('sub_plans',
    sa.Column('id', sa.Integer(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=25), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('position', sa.SmallInteger(), server_default=sa.text('0'), nullable=True),
    sa.PrimaryKeyConstraint('id', name='sub_plans_pkey'),
    sa.UniqueConstraint('title', name='sub_plans_title_key')
    )
    op.create_index('sub_plans_position_idx', 'sub_plans', ['position'], unique=True, postgresql_where='(is_active = true)', postgresql_with={'deduplicate_items': 'true'})
    op.create_table('templates_statuses',
    sa.Column('id', sa.SmallInteger(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=32767, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pattern_statuses_pkey')
    )
    op.create_table('whitelist_commands',
    sa.Column('id', sa.Integer(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('command', sa.String(length=1000), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.PrimaryKeyConstraint('id', name='whitelist_commands_pkey'),
    sa.UniqueConstraint('command', name='whitelist_commands_command_key')
    )
    op.create_table('proto_templates',
    sa.Column('id', sa.SmallInteger(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=32767, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=32), nullable=False),
    sa.Column('status', sa.SmallInteger(), server_default=sa.text('2'), nullable=False),
    sa.Column('url_tmp', sa.Text(), nullable=True),
    sa.Column('is_accepted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('reload_core_command', sa.String(length=128), nullable=True),
    sa.Column('required_user_data_obj', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('constant_user_data_obj', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('api_add_user_script', sa.Text(), nullable=True),
    sa.Column('api_delete_user_script', sa.Text(), nullable=True),
    sa.Column('proto_python_lib', sa.String(length=32), nullable=True),
    sa.Column('flatten_json_users_key', sa.String(length=1024), nullable=True),
    sa.Column('flatten_user_identifier_key', sa.String(length=128), nullable=True),
    sa.Column('sub_prepare_script', sa.Text(), nullable=True),
    sa.Column('sub_required_libs', sa.String(length=512), nullable=True),
    sa.Column('api_bulk_delete_user_script', sa.Text(), nullable=True),
    sa.Column('metrics_parser_code', sa.Text(), nullable=True),
    sa.Column('metrics_command', sa.String(length=256), nullable=True),
    sa.Column('add_script_custom_params', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('delete_script_custom_params', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('bulk_delete_script_custom_params', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('api_metrics_script', sa.Text(), nullable=True),
    sa.Column('api_bulk_add_user_script', sa.Text(), nullable=True),
    sa.Column('bulk_add_script_custom_params', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.ForeignKeyConstraint(['status'], ['templates_statuses.id'], name='proto_templates_status_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='proto_templates_pkey'),
    sa.UniqueConstraint('title', name='proto_templates_title_key')
    )
    op.create_table('sessions_admins',
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('admin_id', sa.BigInteger(), nullable=False),
    sa.Column('iat', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('refresh_token', sa.String(length=97), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('user_agent', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], name='sessions_users_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', name='sessions_users_pkey'),
    sa.UniqueConstraint('refresh_token', name='sessions_users_refresh_token_key'),
    sa.UniqueConstraint('session_id', 'admin_id', name='sessions_users_session_id_user_id_key')
    )
    op.create_table('sub_plan_offers',
    sa.Column('id', sa.Integer(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('sub_plan_id', sa.Integer(), nullable=False),
    sa.Column('ttl_days', sa.SmallInteger(), nullable=False),
    sa.Column('cost', sa.BigInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('traffic_limit_day_mb', sa.BigInteger(), nullable=True),
    sa.Column('traffic_limit_mb', sa.BigInteger(), nullable=True),
    sa.Column('infinite_traffic', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('infinite_expire', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('position', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['sub_plan_id'], ['sub_plans.id'], name='sub_plan_offers_sub_plan_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='sub_plan_offers_pkey')
    )
    op.create_index('sub_plan_offers_position_sub_plan_id_idx', 'sub_plan_offers', ['position', 'sub_plan_id'], unique=True, postgresql_where='(is_active = true)', postgresql_with={'deduplicate_items': 'true'})
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('online_status', sa.SmallInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=True),
    sa.Column('tg_username', sa.String(length=32), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.ForeignKeyConstraint(['online_status'], ['online_statuses.id'], name='users_online_status_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='users_pkey1'),
    sa.UniqueConstraint('tg_id', name='users_tg_id_key'),
    sa.UniqueConstraint('tg_username', name='users_tg_username_key')
    )
    op.create_index('users_tg_id_idx', 'users', ['tg_id'], unique=True, postgresql_where='(is_deleted = false)', postgresql_with={'deduplicate_items': 'true'})
    op.create_index('users_tg_username_idx', 'users', ['tg_username'], unique=True, postgresql_where='(is_deleted = false)', postgresql_with={'deduplicate_items': 'true'})
    op.create_table('pay_orders',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('infinite_expire', sa.Boolean(), nullable=False),
    sa.Column('infinite_traffic', sa.Boolean(), nullable=False),
    sa.Column('cost', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.SmallInteger(), server_default=sa.text('1'), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('traffic_limit_mb', sa.BigInteger(), nullable=True),
    sa.Column('traffic_limit_day_mb', sa.BigInteger(), nullable=True),
    sa.Column('ttl_days', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['status'], ['pay_statuses.id'], name='pay_orders_status_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='pay_orders_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='pay_orders_pkey')
    )
    op.create_table('protocols',
    sa.Column('id', sa.SmallInteger(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=32767, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Название протокола (xray, wireguard, openvpn и т.д.)'),
    sa.Column('tmp_id', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tmp_id'], ['proto_templates.id'], name='protocols_proto_tmp_id_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='protocols_pkey'),
    sa.UniqueConstraint('name', name='protocols_name_key'),
    comment='Пул поддерживаемых VPN протоколов'
    )
    op.create_table('template_spec_params',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('tmp_id', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['tmp_id'], ['proto_templates.id'], name='template_spec_params_tmp_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='template_spec_params_pkey'),
    sa.UniqueConstraint('tmp_id', 'key', name='template_spec_params_tmp_id_key_key')
    )
    op.create_table('nodes_protocols',
    sa.Column('id', sa.Integer(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('proto_id', sa.SmallInteger(), nullable=False),
    sa.Column('node_id', sa.SmallInteger(), nullable=False),
    sa.Column('title', sa.String(length=30), server_default=sa.text("''::character varying"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('config_path', sa.Text(), nullable=True),
    sa.Column('user_visible', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('config_link', sa.Text(), nullable=True),
    sa.Column('metrics_port', sa.Integer(), nullable=True),
    sa.Column('proto_port', sa.Integer(), nullable=True),
    sa.Column('sub_node_address', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], name='nodes_protocols_node_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proto_id'], ['protocols.id'], name='nodes_proto_id_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='nodes_pkey'),
    sa.UniqueConstraint('config_path', 'node_id', name='nodes_protocols_config_path_node_id_key'),
    sa.UniqueConstraint('node_id', 'metrics_port', name='nodes_protocols_node_id_metrics_port_key'),
    sa.UniqueConstraint('node_id', 'proto_port', name='nodes_protocols_node_id_proto_port_key')
    )
    op.create_table('protocols_commands',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('proto_id', sa.SmallInteger(), nullable=False, comment='ID протокола'),
    sa.Column('cmd_title', sa.String(length=200), nullable=False, comment='Название команды (add_user, remove_user, restart и т.д.)'),
    sa.Column('command', sa.Text(), nullable=False, comment='Полная CLI команда для выполнения. Валидация не производится - ответственность администратора'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('admin_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], name='protocols_commands_admin_id_fkey'),
    sa.ForeignKeyConstraint(['proto_id'], ['protocols.id'], name='protocols_commands_proto_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='protocols_commands_pkey'),
    comment='CLI команды для управления протоколами'
    )
    op.create_table('user_subs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('sub_plan_id', sa.Integer(), nullable=False),
    sa.Column('infinite_traffic', sa.Boolean(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('b64_id', sa.String(length=150), nullable=False),
    sa.Column('infinite_expire', sa.Boolean(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('is_limited', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('expire_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('traffic_used_day_mb', sa.BigInteger(), server_default=sa.text('0'), nullable=True),
    sa.Column('traffic_limit_day', sa.BigInteger(), nullable=True),
    sa.Column('used_mb', sa.BigInteger(), server_default=sa.text('0'), nullable=True),
    sa.Column('used_mb_limit', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['pay_orders.id'], name='user_subs_order_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sub_plan_id'], ['sub_plans.id'], name='user_subs_sub_plan_id_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_subs_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_subs_pkey'),
    sa.UniqueConstraint('b64_id', name='user_subs_b64_id_key'),
    sa.UniqueConstraint('user_id', 'sub_plan_id', name='user_subs_user_id_sub_plan_id_key'),
    sa.UniqueConstraint('uuid', name='user_subs_uuid_key')
    )
    op.create_table('nodes_protocoles_spec_params_values',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('spec_key_id', sa.BigInteger(), nullable=False),
    sa.Column('node_proto_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['node_proto_id'], ['nodes_protocols.id'], name='nodes_protocoles_spec_params_values_node_proto_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['spec_key_id'], ['template_spec_params.id'], name='nodes_protocoles_spec_params_values_spec_key_id_fkey', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name='nodes_protocoles_spec_params_values_pkey'),
    sa.UniqueConstraint('spec_key_id', 'node_proto_id', name='nodes_protocoles_spec_params_valu_spec_key_id_node_proto_id_key')
    )
    op.create_table('sub_nodes_outbox',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('user_uuid', sa.String(length=36), nullable=False),
    sa.Column('operation', sa.SmallInteger(), nullable=False),
    sa.Column('user_sub_id', sa.BigInteger(), nullable=False),
    sa.Column('node_proto_id', sa.Integer(), nullable=False),
    sa.Column('is_retried', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['node_proto_id'], ['nodes_protocols.id'], name='sub_nodes_outbox_node_proto_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_sub_id'], ['user_subs.id'], name='sub_nodes_outbox_user_sub_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='sub_nodes_outbox_pkey')
    )
    op.create_table('vnodes_sub_plans',
    sa.Column('id', sa.Integer(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('node_proto_id', sa.Integer(), nullable=False),
    sa.Column('sub_plan_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['node_proto_id'], ['nodes_protocols.id'], name='vnodes_sub_plans_node_proto_id_fkey'),
    sa.ForeignKeyConstraint(['sub_plan_id'], ['sub_plans.id'], name='vnodes_sub_plans_sub_plan_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='vnodes_sub_plans_pkey'),
    sa.UniqueConstraint('node_proto_id', 'sub_plan_id', name='vnodes_sub_plans_node_proto_id_sub_plan_id_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vnodes_sub_plans')
    op.drop_table('sub_nodes_outbox')
    op.drop_table('nodes_protocoles_spec_params_values')
    op.drop_table('user_subs')
    op.drop_table('protocols_commands')
    op.drop_table('nodes_protocols')
    op.drop_table('template_spec_params')
    op.drop_table('protocols')
    op.drop_table('pay_orders')
    op.drop_index('users_tg_username_idx', table_name='users', postgresql_where='(is_deleted = false)', postgresql_with={'deduplicate_items': 'true'})
    op.drop_index('users_tg_id_idx', table_name='users', postgresql_where='(is_deleted = false)', postgresql_with={'deduplicate_items': 'true'})
    op.drop_table('users')
    op.drop_index('sub_plan_offers_position_sub_plan_id_idx', table_name='sub_plan_offers', postgresql_where='(is_active = true)', postgresql_with={'deduplicate_items': 'true'})
    op.drop_table('sub_plan_offers')
    op.drop_table('sessions_admins')
    op.drop_table('proto_templates')
    op.drop_table('whitelist_commands')
    op.drop_table('templates_statuses')
    op.drop_index('sub_plans_position_idx', table_name='sub_plans', postgresql_where='(is_active = true)', postgresql_with={'deduplicate_items': 'true'})
    op.drop_table('sub_plans')
    op.drop_table('sub_nodes_operations')
    op.drop_table('remote_execute_history')
    op.drop_table('pay_statuses')
    op.drop_table('online_statuses')
    op.drop_table('nodes')
    op.drop_table('admins')
    # ### end Alembic commands ###
