services:
  redis:
    image: redis:7.2-alpine
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      bot_net:

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bot
    depends_on:
      web-service:
        condition: service_healthy
    environment:
      - ENV_FILE=/run/secrets/.env.bot.prod
    volumes:
      - ../bot_logs:/app/bot_logs
    secrets:
      - .env.bot.prod
    networks:
      - bot_net
      - api_net

#networks:
#  bot_net:
#    name: ocr_bot_network
#    external: true
#  api_net:
#    name: ocr_web_network
#    external: true

volumes:
  redis_data:
    driver: local

secrets:
  .env.bot.prod:
    file: .env.bot.prod