name: reinar_panel_sub


services:
  sub-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sub-service
    image: reinar_panel/sub_service
    command: python -m web.sub.main
    depends_on:
      pg_db:
        condition: service_healthy
      web-service:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "python -c \"import urllib.request; urllib.request.urlopen('http://localhost:${SUB_PORT}/api/v1/healthcheck')\"" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    #    restart: always
    environment:
      - ENV_FILE=/run/secrets/env.sub.prod
      - RELOAD=1
    network_mode: host
    volumes:
      - ./sub_logs:/app/sub/sub_logs
      - .:/app/web/sub
    secrets:
      - env.sub.prod

  arq-sub-worker:
    container_name: arq-sub-worker
    image: reinar_panel/sub_service
    command: python -m arq web.sub.config_dir.arq_config.WorkerSettings
    depends_on:
      pg_db:
        condition: service_healthy
      sub-service:
        condition: service_healthy
    #    restart: always
    environment:
      - ENV_FILE=/run/secrets/env.sub.prod
    network_mode: host
    volumes:
      - ./arq_logs:/app/sub/arq_logs
      - .:/app/web/sub
    secrets:
      - env.sub.prod


secrets:
  env.sub.prod:
    file: .env.sub.prod