name: test_reinar_panel_sub

# Используется в CI для тестирования
# IMAGE_TAG передается из GitHub Actions с SHA коммита (например: abc1234)
services:
  pg_db:
    image: postgres:16
    container_name: pg_db
    environment:
      - POSTGRES_USER=${PG_ADMIN}
      - POSTGRES_PASSWORD=${PG_ADMIN_PASSWORD}
      - POSTGRES_DB=test_${PG_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${PG_ADMIN}" ]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 30s
    restart: on-failure
    volumes:
      - pgdata:/var/lib/postgresql/data
      #- ../secrets/test_dumps:/docker-entrypoint-initdb.d:z
    ports:
      - "127.0.0.1:${PG_PORT}:5432"

  redis:
    image: redis:7.2-alpine
    container_name: redis
    command:
      - redis-server
      - --requirepass
      - ${REDIS_PASSWORD}
      - --appendonly
      - "yes"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "127.0.0.1:${REDIS_PORT}:6379"

  sub-service:
    image: reinar_panel/web_service:${IMAGE_TAG:-latest}
    command: >
      sh -c "alembic -c web/alembic.ini upgrade head &&
             python web/db/seed_data.py &&
             python -m pytest web/sub/tests -v"
    container_name: test_sub-service
    network_mode: host
    depends_on:
      pg_db:
        condition: service_healthy
    environment:
      - ENV_FILE=/run/secrets/env.sub.test

      - PG_DB=test_${PG_DB}
      - PG_ADMIN=${PG_ADMIN}
      - PG_ADMIN_PASSWORD=${PG_ADMIN_PASSWORD}
      - PG_PORT=${PG_PORT}
      - PG_HOST=localhost
    volumes:
      #- ./secrets/keys:/app/web/secrets/keys:ro
      #      - ../:/app/web
      - ../db:/app/web/db:ro
    secrets:
      - env.sub.test


secrets:
  env.sub.test:
    file: .env.sub.test

volumes:
  pgdata:
    driver: local
  redis_data:
    driver: local